### ISSUE TITLE
Update LocationSearchResultsView

### ISSUE THREAD

**Issue by andreashelms** [trufi-association/trufi-core#220]
![302_list](https://user-images.githubusercontent.com/21622725/51375103-3e913180-1b05-11e9-9013-2ced753daf07.png)
![301_list](https://user-images.githubusercontent.com/21622725/51375110-47820300-1b05-11e9-9f46-8545e0f940cd.png)

**Comment by md-weber** [comment]
I guess this is how it is currently implemented (at least most of it) and I would close the issue. Feel free to open it again if something is missing.
<img src="https://user-images.githubusercontent.com/8026644/114866244-9d80a680-9df3-11eb-9c45-78602d81a921.png" width="200">

**Comment by mdoelker** [comment]
This issue is mainly about the design update and is not really closed. I tried to tackle this once, but it is not trivial to do considering the widget used to display the list and handle scrolling etc is not built to do the visual grouping. There might be ways that I didn't see due to lack of Flutter experience though. It would be nice to have the updated design though.

**Comment by ValorNaram** [comment]
Closing this due to topic inactivity.
