### ISSUE TITLE
Share current position via link

### ISSUE THREAD

**Issue by ZihRah** [trufi-association/trufi-core#623]
I as a user want to share my location with my friends & family members. Therefore I can share a link. The shared link can be opened and the current position is visible.

**Comment by ZihRah** [comment]
Gustavo is doing research on it as it is not that simple as expected.

**Comment by amenk** [comment]
See also #611

**Comment by ZihRah** [comment]
Gustavo has a solution and will try to implement it.

**Comment by ZihRah** [comment]
First test results: It didn't work out.

**Comment by amenk** [comment]
Did this work now? Do you have screenshots?

**Comment by AnivlisLuz** [comment]
@amenk At the moment, it just work with some kind of links, e.g. [Link 1](https://www.google.com/maps/place/Rutilio+Garde,+Cochabamba/@-17.4370721,-66.1291954,18.9z/data=!4m5!3m4!1s0x93e3719ca85149af:0xe58b826a1f7df603!8m2!3d-17.436793!4d-66.1293789?hl=en), [Link 2](https://www.google.com/maps/place/Distribuidora+CADELPA,+0000,+Cochabamba/@-17.4054323,-66.1554869,17z/data=!4m6!3m5!1s0x93e373cbf2e1f753:0xc050b63532a209fc!8m2!3d-17.4054323!4d-66.1554869!16s%2Fg%2F11p08_ct2k), and [Link 3](https://maps.google.com/maps?q=-17.4223147%2C-66.1442717&z=17&hl=es). After you select one of these, the option to open with the app is available, when you select the app a message is displayed to set it as Origin or Destination (See screenshots)

![image](https://github.com/trufi-association/trufi-core/assets/42398857/f8469586-aff0-4ec0-93c6-2679ccdccd5e)

![image](https://github.com/trufi-association/trufi-core/assets/42398857/758e1d2a-df4d-4aeb-9992-7842d8e995f0)

**Comment by amenk** [comment]
Thank you.

Clicking the links and opening them in Trufi did not work in my tests, but might be related to my phone's settings.

Anyways, I there also a function in Trufi to share such a link?

**Comment by AnivlisLuz** [comment]
Could you tell us details about your phone? 
But just in case, this option does not work in iphone, but we are reviewing that. Then in my case (An android) I have to made some changes in phone's settings, I modifyed default applications because this kind of links was just opened by Google maps app.

Trufi shares links after made a request, and also when you search for an specific route in the "Show route" option. See Screenshots:

![Show route](https://github.com/trufi-association/trufi-core/assets/42398857/7fa1107b-ccee-4624-92a2-72fbaf531008)

![Request](https://github.com/trufi-association/trufi-core/assets/42398857/7da1f5b0-5ac3-4b97-91e7-021c0671cc6d)
